# Generated by Django 6.0.3 on 2026-06-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='lessons/images/')),
                ('audio', models.FileField(upload_to='lessons/audio/')),
                ('video', models.FileField(upload_to='lessons/videos/')),
                ('pdf', models.FileField(upload_to='lessons/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
