# Generated by Django 6.0.3 on 2026-06-01 12:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = []

    operations = []
